spring:
  datasource:
    url: ENC(CEzgQy+aBpr9uWY1q7jbOghhORC/YrlCiIKIDogM4NBKP16aUCPmBdbqjOS06bNWbg/uo+DnOwa5JPS4At+XMKe0MT2nkTVSiyKqutwB9a80Vbcnij5NrsIICRoGNIKyk4d0x7UfASQS39QHDZIfPGZAyf+E5yYb3191hDiUT+Ec9rVBsHDBOQt9/AHTJTxkK6oDyGBMIIh7GNaVgqGV8g==)
    username: ENC(Y09lm2M1M+zwDAt6nnbyiQPL31nnSscqCvpqchGX93XD0Vi3rJyniuzR/k8Ma7Ft)
    password: ENC(9SU3CK03P/IVXqiU5wOtKm4tsrX87xL22cdTUaykRvYJ9q8g9796I3X8o4gEN7T7)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true

server:
  port: 5000
  ssl:
    enabled: false
    key-store: classpath:ssl/keystore.p12
    key-store-password: ENC(lK2PUwcQSfKYIGzkiu+9ZU4eTWSv1uBffigjXy3HbEwAYBaP0QL2h0qi71Gc09xmnPYilOajqwrhap/dCiI2Og==)
    key-store-type: PKCS12
    key-alias: tomcat

# PatreonShout
patreonshout:
  client: # Client Configuration
    id: ENC(nMre8DN4MIfqWboHBpuhZ2uSt+ALas/qviUiENIBaEfFfhC7jl8codJpu/WOWCRet/j+Bj+dne/KMT5LYuMuknchRIOASP/M2URBj0CnVZfet16q/IBSvwDaR6+2ES1r9T+0ufrZTbfEOTfqbU/87A==)
    secret: ENC(QKxPWLxCi3M5dc43o1LjTr4X/T4XIowYuuw3NxHR7Ch1Sp2Q5YuKKPJAo3hLx2n9kQ6WNfuQNcuRSar922Ca0ryJu6J5vXwMF4nP5b9mW/nDgk+6uDpAq74OOwLUhw+rE1j8evg02B9oFSGAyDN4+A==)
    redirecturi: https://prodprod.backend.outofstonk.com
  db: # Database Configuration
    webaccount:
      pepper: ENC(BLaHIgDKQVzb0giPFe+TXRCuUkKd/rwfraIpagzIyChf6fA+A/btX2xrPihjfQwo)

# Twitter
twitter:
  client: #Client Configuration
    id: ENC(z9gF7PIUw6A+OAIrLhyC5wZsStdhUrvbMHyoXYRAdJG92WwDtxBghPl4RiVzO2247pkt9zReUHJdyhgy8rLhOrjGNtUiDGQKFnsuj4uJrgk=)
    secret: ENC(HSrCIi/Bn8LX+hhz/RhnjMVjhMSuCROLIgZlBxZacFlMG+cn2WdK5oAOuO4Wm2FonJTUX7JzZwsJmJyjclfowngxj1Xv6DIOfS65ZPTjOOyNga4vYft3PmiqcsNR3yps)
    redirecturi: https://prodprod.backend.outofstonk.com/receivers/twitter/oauth

# Reddit
reddit:
  client:
    id:
    secret:
    redirecturi: https://prodprod.backend.outofstonk.com/receivers/reddit/oauth