spring:
  datasource:
    url: ENC(NIHnrI2i9J4FNQOSxSXOojUfWLMuAmUz4sYJuV8Hi+Y0HpZ9l3rsC9Zu6rudQxdndzNoyWAN7kx0oDv0AzHdothuE5C/ULX3JwH3Bj/ukPKL5zL2mWWaFv1LTzuHHph8/jpFJF3N5qRMKBaYhoaDh6ZzZ0gYgg/FiEgsyxZq3Qyl/7CVQm1e0Xbon2aQdd6JL6TWOrnpkCT4Ul1rgzXaOw==)
    username: ENC(MFzOoQS5aBXmqmIYsx2bEfcKRuhNp+P4g4c+cANVlTF3qZTxz8XLf5zJ3I088ofx)
    password: ENC(ySpRJnFcRFQXXLh+4FdrMpNEXyHsb2L6MieADLstMUDmRPxh3fWA6NjZXf+H5jC4)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true

server:
  port: 5000

  # HTTPS Configuration
  # Tutorial:
  #   - Generate PEM files with: https://www.digitalocean.com/community/tutorials/how-to-acquire-a-let-s-encrypt-certificate-using-dns-validation-with-acme-dns-certbot-on-ubuntu-18-04
  #   - Convert PEM files to PKCS12 https://dzone.com/articles/spring-boot-secured-by-lets-encrypt
  ssl:
    enabled: false
    key-store: classpath:ssl/keystore.p12
    key-store-password: ENC(lK2PUwcQSfKYIGzkiu+9ZU4eTWSv1uBffigjXy3HbEwAYBaP0QL2h0qi71Gc09xmnPYilOajqwrhap/dCiI2Og==)
    key-store-type: PKCS12
    key-alias: tomcat

# PatreonShout
patreonshout:
  client: # Client Configuration
    id: Aymjq1-b_ZkmaeejretFStklrikzMGcG-LEtCkt3GvOeiuOO2MY0_hluLoUzC4ce
    secret: PgFjamxT-DlenUKEqlf2px49QgYFd3a-MlSzoYzuuUxQepgDK_ajCYs8xbqrsLLB
    redirecturi: http://localhost:5000
  db: # Database Configuration
    webaccount:
      pepper: ENC(BLaHIgDKQVzb0giPFe+TXRCuUkKd/rwfraIpagzIyChf6fA+A/btX2xrPihjfQwo)

# Twitter
twitter:
  client: #Client Configuration
    id: ENC(jO5qy6HDhQK0COh8IhiwbGpig8XkdoMyNWC+62BsQNitT2eFOT4DMnpu4hVpsO3WNwzJAUzyD74G8TfzzWHTmjXdDk8rJKP9QKTOFlSjgDc=)
    secret: ENC(/4d4clyxR5qUNV17KqYAtUZETLzwrdMbbr6prFJAvfdjXJhsUDQ1ZqBwCE+IBua/23Ve5B7H//VuyKpooa06+5ZXLMVG/iLyTvdZCAA+92Gjomo7KGDp2nF7NaEv6kM3)
    redirecturi: ${patreonshout.client.redirecturi}/receivers/twitter/oauth

# Instagram
instagram:
  client:
    id: ENC(M5W+h39khivgs+aiSMRy52jITx/1XI+xMIz8f9xIA2wyXqfa8zCIPDEDAvMA4zoL)
    secret: ENC(tGddH5ds1aRWgI04ocs6XHFQnrI+gWTRuFQqWqX2RkkaCPGNeYpFunkgQyR4TfOIMrjoI8d/CYEj769NhttXBtolfYfd+nd3121pXqaEnJw=)
    redirecturi: ${patreonshout.client.redirecturi}/receivers/instagram/oauth

# Reddit
reddit:
  client:
    id: ENC(3LzHZ5WOYu8H0oswIy1Siy8Ts6l+rOlUm8ElRLxuho32FmMer9V1t+LhkEngDCAJidsY69h+2sSifoBQNOejDw==)
    secret: ENC(Ov88GuEjjW2YkMxNVzIcgdXgKrZ/4zmnOn4KuOa7jO16wiL/YmkM1dZBA91hROHmBjDfkTI7urAeHSavyzwClQ==)
    redirecturi: ${patreonshout.client.redirecturi}/receivers/reddit/oauth