openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:5000
    description: Generated server url
tags:
  - name: Patreon Info service
    description: Handles all Patreon Info related tasks for the database.
  - name: Web Account Service
    description: Handles all Web Account related tasks for the database.
paths:
  /patreoninfo/put:
    put:
      tags:
        - Patreon Info service
      summary: Saves Content Creator Patreon Information
      operationId: PutPatreonInfo
      requestBody:
        description: Patreon Info To Add
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatreonInfoBean'
        required: true
      responses:
        '200':
          description: Patreon Information was saved
          content:
            application/json: {}
        '409':
          description: Patreon Information was not saved
          content:
            application/json: {}
  /webaccount/register:
    get:
      tags:
        - Web Account Service
      summary: Registers WebAccounts during PatreonShout sign up
      operationId: Register
      parameters:
        - name: user
          in: query
          required: true
          schema:
            type: string
        - name: pass
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: WebAccount has been registered
          content:
            application/json: {}
        '409':
          description: Username already exists
          content:
            application/json: {}
  /v1/webhook:
    get:
      tags:
        - o-auth-test
      operationId: WebhookReceiver
      parameters:
        - name: code
          in: query
          required: false
          schema:
            type: string
        - name: state
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK
components:
  schemas:
    PatreonInfoBean:
      type: object
      properties:
        patreon_info_id:
          type: integer
          format: int32
        access_token:
          type: string
        scope:
          type: string
        expires_in:
          type: integer
          format: int32
