name: DEV Deploy Backend
on:
  push:
    branches:
      - "feature/*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.4
        with:
          maven-version: 3.8.2

      - name: Build with Maven
        run: cd gateway && mvn clean install -Dmaven.test.skip=true && cd ..

      - name: Get current time
        uses: josStorer/get-current-time@v2.0.2
        id: current-time
        with:
          format: YYYYMMDD-HH
          utcOffset: "-05:00"

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_DEV_BACKEND_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_DEV_BACKEND_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.AWS_DEV_BACKEND_APPLICATION_NAME }}
          environment_name: ${{ secrets.AWS_DEV_BACKEND_ENVIRONMENT_NAME }}
          version_label: ${{ github.run_attempt }}-${{ steps.date.outputs.date }}-${{ steps.current-time.outputs.ISOTime }}
          version_description: ${{github.SHA}}
          region: us-east-2
          deployment_package: gateway/target/gateway.jar